services:
  frontend:
    image: tcyber_frontend:offline
    container_name: tcyber_frontend
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://127.0.0.1:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - tcyber_network
