"""Test shim for `prometheus_client`.

This file prefers the real `prometheus_client` package when available
so CI and developer environments that install it will use the real
implementation. When the real package is not installed (local dev or
lightweight test runs), the shim provides a minimal, safe subset used
by unit tests in this repository.

NOTE: This is a test shim. If CI/production environments install the
real `prometheus_client`, this shim will delegate to the real package.
"""
from typing import Any


try:
    # If the real prometheus_client is installed, re-export its symbols.
    import prometheus_client as _real_prom

    CollectorRegistry = _real_prom.CollectorRegistry
    generate_latest = _real_prom.generate_latest
    Counter = _real_prom.Counter
    Gauge = _real_prom.Gauge
    Histogram = _real_prom.Histogram

except Exception:
    # Fallback shim used for lightweight test runs where the package
    # is not available. Keep behavior simple and deterministic.

    class CollectorRegistry:
        def __init__(self, auto_describe: bool = True):
            self._metrics = []

        def register_metric(self, name: str):
            if name not in self._metrics:
                self._metrics.append(name)


    def generate_latest(registry: CollectorRegistry) -> bytes:
        # Return simple text payload containing metric names for tests
        lines = []
        for name in getattr(registry, "_metrics", []):
            lines.append(f"# HELP {name} autogenerated shim")
            lines.append(f"# TYPE {name} counter")
            lines.append(f"{name} 0")
        return "\n".join(lines).encode("utf-8")


    class _BaseMetric:
        def __init__(self, *args, **kwargs):
            # register metric name in provided registry if present
            try:
                name = args[0] if args else None
                registry = kwargs.get("registry")
                if name and registry is not None:
                    registry.register_metric(name)
            except Exception:
                pass

        def inc(self, v: float = 1.0):
            pass

        def set(self, v: float):
            pass


    class Counter(_BaseMetric):
        pass


    class Gauge(_BaseMetric):
        pass


    class Histogram(_BaseMetric):
        def observe(self, v: float):
            pass
