"""Test shim for `prometheus_client` (moved into tests/_shims).

This copy is a minimal fallback used in lightweight test runs.
"""
from typing import Any


try:
    import prometheus_client as _real_prom

    CollectorRegistry = _real_prom.CollectorRegistry
    generate_latest = _real_prom.generate_latest
    Counter = _real_prom.Counter
    Gauge = _real_prom.Gauge
    Histogram = _real_prom.Histogram

except Exception:
    class CollectorRegistry:
        def __init__(self, auto_describe: bool = True):
            self._metrics = []

        def register_metric(self, name: str):
            if name not in self._metrics:
                self._metrics.append(name)


    def generate_latest(registry: CollectorRegistry) -> bytes:
        lines = []
        for name in getattr(registry, "_metrics", []):
            lines.append(f"# HELP {name} autogenerated shim")
            lines.append(f"# TYPE {name} counter")
            lines.append(f"{name} 0")
        return "\n".join(lines).encode("utf-8")


    class _BaseMetric:
        def __init__(self, *args, **kwargs):
            try:
                name = args[0] if args else None
                registry = kwargs.get("registry")
                if name and registry is not None:
                    registry.register_metric(name)
            except Exception:
                pass

        def inc(self, v: float = 1.0):
            pass

        def set(self, v: float):
            pass


    class Counter(_BaseMetric):
        pass


    class Gauge(_BaseMetric):
        pass


    class Histogram(_BaseMetric):
        def observe(self, v: float):
            pass
